"""domain tag

Revision ID: 3321586ad6c4
Revises: 7c2a518ed636
Create Date: 2021-11-27 19:30:48.062908

"""
import sqlalchemy as sa
import sqlmodel
import sqlmodel.sql.sqltypes
from alembic import op

# revision identifiers, used by Alembic.
revision = "3321586ad6c4"
down_revision = "7c2a518ed636"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "domains",
        sa.Column(
            "tag", sqlmodel.sql.sqltypes.AutoString(), server_default="", nullable=False
        ),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("domains", "tag")
    # ### end Alembic commands ###
