"""remove languages in problem_config

Revision ID: 3af1be6020d1
Revises: b74e9831f731
Create Date: 2022-05-11 13:49:31.028359

"""
import sqlalchemy as sa
import sqlmodel
import sqlmodel.sql.sqltypes
from alembic import op
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = "3af1be6020d1"
down_revision = "b74e9831f731"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("problem_configs", "languages")
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "problem_configs",
        sa.Column(
            "languages",
            postgresql.JSON(astext_type=sa.Text()),
            server_default=sa.text("'[]'::json"),
            autoincrement=False,
            nullable=False,
        ),
    )
    # ### end Alembic commands ###
