"""remove unique constraint for ProblemProblemSetLink

Revision ID: 461fe2b71f78
Revises: fda892db1717
Create Date: 2021-12-15 05:00:42.381756

"""
import sqlalchemy as sa
import sqlmodel
import sqlmodel.sql.sqltypes
from alembic import op

# revision identifiers, used by Alembic.
revision = "461fe2b71f78"
down_revision = "fda892db1717"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(
        "problem_problem_set_links_problem_set_id_position_key",
        "problem_problem_set_links",
        type_="unique",
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(
        "problem_problem_set_links_problem_set_id_position_key",
        "problem_problem_set_links",
        ["problem_set_id", "position"],
    )
    # ### end Alembic commands ###
