"""add tag to domain

Revision ID: 538579eca05b
Revises: 3af1be6020d1
Create Date: 2022-05-20 21:14:30.373934

"""
import sqlalchemy as sa
import sqlmodel
import sqlmodel.sql.sqltypes
from alembic import op

# revision identifiers, used by Alembic.
revision = "538579eca05b"
down_revision = "3af1be6020d1"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "domains", sa.Column("tag", sqlmodel.sql.sqltypes.AutoString(), nullable=True)
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("domains", "tag")
    # ### end Alembic commands ###
