"""user latest record

Revision ID: 7c2a518ed636
Revises: fe2df95ee61a
Create Date: 2021-11-27 15:37:54.561822

"""
import sqlalchemy as sa
import sqlmodel
import sqlmodel.sql.sqltypes
from alembic import op

# revision identifiers, used by Alembic.
revision = "7c2a518ed636"
down_revision = "fe2df95ee61a"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "user_latest_records",
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("TIMEZONE('utc', CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("TIMEZONE('utc', CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.Column("user_id", sqlmodel.sql.sqltypes.GUID(), nullable=False),
        sa.Column("problem_id", sqlmodel.sql.sqltypes.GUID(), nullable=False),
        sa.Column("problem_set_id", sqlmodel.sql.sqltypes.GUID(), nullable=True),
        sa.Column("record_id", sqlmodel.sql.sqltypes.GUID(), nullable=False),
        sa.Column("id", sqlmodel.sql.sqltypes.GUID(), nullable=False),
        sa.ForeignKeyConstraint(["problem_id"], ["problems.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(
            ["problem_set_id"], ["problem_sets.id"], ondelete="CASCADE"
        ),
        sa.ForeignKeyConstraint(["record_id"], ["records.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["user_id"], ["users.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("user_id", "problem_id", "problem_set_id", "record_id"),
    )
    op.create_index(
        op.f("ix_user_latest_records_created_at"),
        "user_latest_records",
        ["created_at"],
        unique=False,
    )
    op.create_index(
        op.f("ix_user_latest_records_id"), "user_latest_records", ["id"], unique=False
    )
    op.create_index(
        op.f("ix_user_latest_records_updated_at"),
        "user_latest_records",
        ["updated_at"],
        unique=False,
    )
    op.add_column(
        "problem_configs",
        sa.Column(
            "commit_message",
            sqlmodel.sql.sqltypes.AutoString(),
            server_default="",
            nullable=False,
        ),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("problem_configs", "commit_message")
    op.drop_index(
        op.f("ix_user_latest_records_updated_at"), table_name="user_latest_records"
    )
    op.drop_index(op.f("ix_user_latest_records_id"), table_name="user_latest_records")
    op.drop_index(
        op.f("ix_user_latest_records_created_at"), table_name="user_latest_records"
    )
    op.drop_table("user_latest_records")
    # ### end Alembic commands ###
