"""domain groups

Revision ID: bf20e6255b48
Revises: 0beef02ef1dc
Create Date: 2022-02-19 13:34:15.718583

"""
import sqlalchemy as sa
import sqlmodel
import sqlmodel.sql.sqltypes
from alembic import op

# revision identifiers, used by Alembic.
revision = "bf20e6255b48"
down_revision = "0beef02ef1dc"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index("ix_domain_invitations_id", table_name="domain_invitations")
    op.drop_index("ix_domain_roles_id", table_name="domain_roles")
    op.drop_index("ix_domain_users_id", table_name="domain_users")
    op.add_column(
        "domains",
        sa.Column(
            "group",
            sqlmodel.sql.sqltypes.AutoString(),
            server_default="",
            nullable=False,
        ),
    )
    op.drop_index("ix_domains_id", table_name="domains")
    op.drop_column("domains", "tag")
    op.drop_index("ix_problem_configs_id", table_name="problem_configs")
    op.drop_index("ix_problem_groups_id", table_name="problem_groups")
    op.create_index(
        op.f("ix_problem_problem_set_links_position"),
        "problem_problem_set_links",
        ["position"],
        unique=False,
    )
    op.drop_index("ix_problem_sets_id", table_name="problem_sets")
    op.drop_index("ix_problems_id", table_name="problems")
    op.drop_index("ix_records_id", table_name="records")
    op.drop_index("ix_user_access_keys_id", table_name="user_access_keys")
    op.drop_index("ix_user_latest_records_id", table_name="user_latest_records")
    op.drop_index("ix_user_oauth_accounts_id", table_name="user_oauth_accounts")
    op.drop_index("ix_users_id", table_name="users")
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index("ix_users_id", "users", ["id"], unique=False)
    op.create_index(
        "ix_user_oauth_accounts_id", "user_oauth_accounts", ["id"], unique=False
    )
    op.create_index(
        "ix_user_latest_records_id", "user_latest_records", ["id"], unique=False
    )
    op.create_index("ix_user_access_keys_id", "user_access_keys", ["id"], unique=False)
    op.create_index("ix_records_id", "records", ["id"], unique=False)
    op.create_index("ix_problems_id", "problems", ["id"], unique=False)
    op.create_index("ix_problem_sets_id", "problem_sets", ["id"], unique=False)
    op.drop_index(
        op.f("ix_problem_problem_set_links_position"),
        table_name="problem_problem_set_links",
    )
    op.create_index("ix_problem_groups_id", "problem_groups", ["id"], unique=False)
    op.create_index("ix_problem_configs_id", "problem_configs", ["id"], unique=False)
    op.add_column(
        "domains",
        sa.Column(
            "tag",
            sa.VARCHAR(),
            server_default=sa.text("''::character varying"),
            autoincrement=False,
            nullable=False,
        ),
    )
    op.create_index("ix_domains_id", "domains", ["id"], unique=False)
    op.drop_column("domains", "group")
    op.create_index("ix_domain_users_id", "domain_users", ["id"], unique=False)
    op.create_index("ix_domain_roles_id", "domain_roles", ["id"], unique=False)
    op.create_index(
        "ix_domain_invitations_id", "domain_invitations", ["id"], unique=False
    )
    # ### end Alembic commands ###
