"""add languages to problem

Revision ID: ca13cabaea42
Revises: bf20e6255b48
Create Date: 2022-05-04 05:19:35.641513

"""
import sqlalchemy as sa
import sqlmodel
import sqlmodel.sql.sqltypes
from alembic import op

# revision identifiers, used by Alembic.
revision = "ca13cabaea42"
down_revision = "bf20e6255b48"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "problems",
        sa.Column("languages", sa.JSON(), server_default="[]", nullable=False),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("problems", "languages")
    # ### end Alembic commands ###
