"""record task id

Revision ID: fda892db1717
Revises: 3321586ad6c4
Create Date: 2021-12-13 21:11:39.644737

"""
import sqlalchemy as sa
import sqlmodel
import sqlmodel.sql.sqltypes
from alembic import op
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = "fda892db1717"
down_revision = "3321586ad6c4"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "records", sa.Column("task_id", sqlmodel.sql.sqltypes.GUID(), nullable=True)
    )
    op.drop_column("records", "toolchains")
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "records",
        sa.Column(
            "toolchains",
            postgresql.JSON(astext_type=sa.Text()),
            server_default=sa.text("'[]'::json"),
            autoincrement=False,
            nullable=False,
        ),
    )
    op.drop_column("records", "task_id")
    # ### end Alembic commands ###
