# This workflow will install Python dependencies, run tests and lint with a variety of Python versions
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-python-with-github-actions

name: Python package

on: [ push ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Set up Python 3.9
      uses: actions/setup-python@v2
      with:
        python-version: 3.9
    - name: Cache environment
      uses: actions/cache@v2
      id: cache
      with:
        path: ${{ env.pythonLocation }}
        key: ${{ runner.os }}-${{ env.pythonLocation }}-${{ secrets.CACHE_VERSION }}-${{ hashFiles('**/setup.py') }}-${{ hashFiles('**/requirements.txt') }}
        restore-keys: |
          ${{ runner.os }}-${{ env.pythonLocation }}
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        if [ -f requirements.txt ]; then pip install -e .; fi
    - name: Git setup
      uses: fregante/setup-git-user@v1
    - name: Generate openapi.json
      run: |
        mkdir -p build
        python3 -m joj.horse.openapi > build/openapi.json
    - name: Git push openapi.json
      if: success() && github.event_name == 'push' && github.ref == 'refs/heads/master'
      uses: crazy-max/ghaction-github-pages@v2
      with:
        target_branch: openapi
        build_dir: build
        keep_history: true
        commit_message: Generate openapi.json
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    - name: Git push openapi.json (develop)
      if: success() && github.event_name == 'push' && github.ref == 'refs/heads/develop'
      uses: crazy-max/ghaction-github-pages@v2
      with:
        target_branch: openapi-develop
        build_dir: build
        keep_history: true
        commit_message: Generate openapi.json (develop)
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
