# This workflow will install Python dependencies, run tests and lint with a variety of Python versions
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-python-with-github-actions

name: Python package

on:
  push:
    branches:
      - master
      - develop
  pull_request:
    branches:
      - master
      - develop

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Set up Python 3.9
      uses: actions/setup-python@v2
      with:
        python-version: 3.9
    - name: Cache environment
      uses: actions/cache@v2
      id: cache
      with:
        path: /opt/hostedtoolcache/Python/3.9.1/x64/lib/python3.9/site-packages/*
        key: ${{ runner.os }}-pip-${{ hashFiles('**/requirements.txt') }}
        restore-keys: |
          ${{ runner.os }}-pip-
    - name: Install dependencies
      if: steps.cache.outputs.cache-hit != 'true'
      run: |
        python -m pip install --upgrade pip
        if [ -f requirements.txt ]; then pip install -e .; fi
    - name: Git setup
      uses: fregante/setup-git-user@v1
    - name: Generate openapi.tmp.json
      run: |
        python3 -m joj.horse.openapi > openapi.tmp.json
    - name: Git checkout & add & commit & push
      run: |
        git fetch
        git checkout openapi || git checkout -b openapi
        mv -f openapi.tmp.json openapi.json
        git status
        git add openapi.json
        git commit -m 'update openapi.json'
        git push --set-upstream origin openapi
        git status
